services:
    server:
        build:
            context: ..
            dockerfile: bot/Dockerfile
        environment:
            - CLIENT_ID=${CLIENT_ID}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - API_BASE_URL=${API_BASE_URL}
            - ENABLE_MOCK_API=${ENABLE_MOCK_API}
            - BETTERSTACK_HEARTBEAT_URL=${BETTERSTACK_HEARTBEAT_URL}
        ports:
            - 3000:3000
